- repo: https://git.mif.vu.lt/mapl2005/authentication-webapp-project
  # Ruff version.
  rev: v0.15.12
  hooks:
    # Run the linter.
    - id: ruff-check
    # Run the formatter.
    - id: ruff-format
