"""
Stateful Authentication Module.

This module handles dynamic login processes for web vulnerability scanning.
It navigates to a target URL, extracts hidden CSRF tokens, submits credentials,
and returns an active session object to be used by the main scanning engine.
"""

import argparse
import requests
from bs4 import BeautifulSoup

def get_cli_arguments():
    """
    Parses command-line arguments provided by the user in the terminal.

    Returns:
        dict: A dictionary containing the target URL, credentials,
              HTML field attributes, and the success indicator string.
    """
    print("\n Initializing Command-Line Argument Parser...")
    parser = argparse.ArgumentParser(description="Stateful Authentication Module")

    parser.add_argument('--url', required=True, help="Target login URL")
    parser.add_argument('--user', required=True, help="Username to inject")
    parser.add_argument('--password', required=True, help="Password to inject")
    parser.add_argument('--user-field', required=True, help="HTML name attribute for username")
    parser.add_argument('--pass-field', required=True, help="HTML name attribute for password")
    parser.add_argument('--csrf-field', required=True, help="HTML name attribute for CSRF token")
    parser.add_argument('--success-string', required=True, help="Text on the page that confirms login success (e.g., 'Welcome', 'Dashboard')")

    args = parser.parse_args()

    return {
        'login_url': args.url,
        'username': args.user,
        'password': args.password,
        'user_field': args.user_field,
        'pass_field': args.pass_field,
        'csrf_field': args.csrf_field,
        'success_string': args.success_string
    }

def authenticate(config):
    """
    Performs the stateful authentication process against the target.

    Args:
        config (dict): The target configuration dictionary generated by get_cli_arguments().

    Returns:
        requests.Session: An authenticated session object if successful, or None if it fails.
    """
    print("Initializing stateful session (Cookie Jar)...")
    session = requests.Session()

    print(f"Visiting {config['login_url']} to extract the CSRF token...")

    try:
        response = session.get(config['login_url'], timeout=10)

        response.raise_for_status()

    except requests.exceptions.RequestException as e:
        print(f"FATAL: Could not reach the target URL ({config['login_url']}).")
        print(f"Error details: {e}")
        return None

    soup = BeautifulSoup(response.text, 'html.parser')
    token_input = soup.find('input', {'name': config['csrf_field']})

    if not token_input:
        print("Error: Could not find the CSRF token on the page!")
        return None

    csrf_token = token_input.get('value')
    print(f"Found hidden CSRF Token: {csrf_token}")

    login_data = {
        config['user_field']: config['username'],
        config['pass_field']: config['password'],
        config['csrf_field']: csrf_token,
        'Login': 'Login'
    }

    print("Submitting login credentials and token...")
    try:
        login_response = session.post(config['login_url'], data=login_data, timeout=10)
        login_response.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"FATAL: Failed to submit login data to ({config['login_url']}).")
        print(f"Error details: {e}")
        return None

# Check if the user's custom success string is in the response
    if config['success_string'] in login_response.text:
        print("[SUCCESS] Authentication Successful! The session is active.")
        return session
    else:
        print("Authentication Failed. Success string not found in response.")
        return None

if __name__ == "__main__":
    target_config = get_cli_arguments()
    active_session = authenticate(target_config)

    if active_session:
        print(f"Current Session Cookies: {active_session.cookies.get_dict()}")