"""
Stateful Authentication Module.

This module handles dynamic login processes for web vulnerability scanning.
It navigates to a target URL, extracts hidden CSRF tokens, submits credentials,
and returns an active session object to be used by the main scanning engine.
"""

import argparse
import requests
from bs4 import BeautifulSoup

def get_cli_arguments():
    """
    Parses command-line arguments provided by the user in the terminal.

    Returns:
        dict: A dictionary containing the target URL, credentials,
              HTML field attributes, and the success indicator string.
    """
    print("\n Initializing Command-Line Argument Parser...")
    parser = argparse.ArgumentParser(description="Stateful Authentication Module")

    parser.add_argument('--url', required=True, help="Target Login URL")
    parser.add_argument('--user', required=True, help="Username to inject")
    parser.add_argument('--password', required=True, help="Password to inject")
    parser.add_argument('--success-string', required=True, help="Text indicating successful login")

    #"traffic cop" flag
    parser.add_argument('--auth-type', required=True, choices=['form', 'basic', 'json'], help="Type of login mechanism")

    parser.add_argument('--user-field', required=False, help="HTML name or JSON key for username")
    parser.add_argument('--pass-field', required=False, help="HTML name or JSON key for password")
    parser.add_argument('--csrf-field', required=False, help="HTML name for CSRF token (Form only)")

    args = parser.parse_args()

    return {
        'login_url': args.url,
        'username': args.user,
        'password': args.password,
        'success_string': args.success_string,
        'auth_type': args.auth_type,
        'user_field': args.user_field,
        'pass_field': args.pass_field,
        'csrf_field': args.csrf_field
    }

def authenticate(config):
    """
    Routes the authentication request to the correct strategy based on CLI arguments.
    """
    print(f"Initializing stateful session (Strategy: {config['auth_type'].upper()})...")
    session = requests.Session()

    if config['auth_type'] == 'form':
        return do_form_login(session, config)

    elif config['auth_type'] == 'basic':
        return do_basic_login(session, config)

    elif config['auth_type'] == 'json':
        return do_json_login(session, config)

def do_form_login(session, config):
    """
    Handles standard HTML forms with CSRF tokens.

    Args:
        config (dict): The target configuration dictionary generated by get_cli_arguments().

    Returns:
        requests.Session: An authenticated session object if successful, or None if it fails.
    """
    print(f"Visiting {config['login_url']} to extract the CSRF token...")

    try:
        response = session.get(config['login_url'], timeout=10)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"FATAL: Could not reach the target URL ({config['login_url']}).")
        print(f"Error details: {e}")
        return None

    soup = BeautifulSoup(response.text, 'html.parser')
    token_input = soup.find('input', {'name': config['csrf_field']})

    if not token_input:
        print("Error: Could not find the CSRF token on the page!")
        return None

    csrf_token = token_input.get('value')
    print(f"Found hidden CSRF Token: {csrf_token}")

    login_data = {
        config['user_field']: config['username'],
        config['pass_field']: config['password'],
        config['csrf_field']: csrf_token,
        'Login': 'Login'
    }

    print("Submitting login credentials and token...")
    try:
        login_response = session.post(config['login_url'], data=login_data, timeout=10)
        login_response.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"FATAL: Failed to submit login data.")
        return None

    if config['success_string'] in login_response.text:
        print("[SUCCESS] Form Authentication Successful! The session is active.")
        return session
    else:
        print("Authentication Failed. Success string not found.")
        return None

def do_basic_login(session, config):
    """Handles HTTP Basic Authentication (Browser Pop-ups)."""
    print(f"Attempting HTTP Basic Auth at {config['login_url']}...")

    try:
        response = session.get(config['login_url'], auth=(config['username'], config['password']), timeout=10)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"FATAL: Basic Auth request failed.")
        print(f"Error details: {e}")
        return None

    if config['success_string'] in response.text:
        print("[SUCCESS] HTTP Basic Auth Successful! The session is active.")
        return session
    else:
        print("Basic Auth Failed. Success string not found.")
        return None

def do_json_login(session, config):
    """Handles Modern API Authentication sending application/json."""
    print(f"Attempting JSON API Auth at {config['login_url']}...")

    json_payload = {
        config['user_field']: config['username'],
        config['pass_field']: config['password']
    }

    try:
        response = session.post(config['login_url'], json=json_payload, timeout=10)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"FATAL: JSON API Auth request failed.")
        print(f"Error details: {e}")
        return None

    if config['success_string'] in response.text:
        print("[SUCCESS] JSON API Auth Successful! The session is active.")
        return session
    else:
        print("JSON API Auth Failed. Success string not found.")
        return None

if __name__ == "__main__":
    target_config = get_cli_arguments()
    active_session = authenticate(target_config)

    if active_session:
        print(f"Current Session Cookies: {active_session.cookies.get_dict()}")